// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDx40lqRMUVq47_2w34r_cLvy1lzpnN9M',
    appId: '1:1093295036929:web:9eecd209fcd724b2317e00',
    messagingSenderId: '1093295036929',
    projectId: 'fall-detection-project-c06ac',
    authDomain: 'fall-detection-project-c06ac.firebaseapp.com',
    storageBucket: 'fall-detection-project-c06ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqIEcQJTDsrFdcrFRmi629x_CNgj3f68A',
    appId: '1:1093295036929:android:31effd1ebe72a885317e00',
    messagingSenderId: '1093295036929',
    projectId: 'fall-detection-project-c06ac',
    storageBucket: 'fall-detection-project-c06ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCPACjwl9DBz_U5PsHp9gpmL_mExnHXxc',
    appId: '1:1093295036929:ios:ec9f56149453cd9f317e00',
    messagingSenderId: '1093295036929',
    projectId: 'fall-detection-project-c06ac',
    storageBucket: 'fall-detection-project-c06ac.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCPACjwl9DBz_U5PsHp9gpmL_mExnHXxc',
    appId: '1:1093295036929:ios:ec9f56149453cd9f317e00',
    messagingSenderId: '1093295036929',
    projectId: 'fall-detection-project-c06ac',
    storageBucket: 'fall-detection-project-c06ac.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDx40lqRMUVq47_2w34r_cLvy1lzpnN9M',
    appId: '1:1093295036929:web:8c4889d5e7f1b3f0317e00',
    messagingSenderId: '1093295036929',
    projectId: 'fall-detection-project-c06ac',
    authDomain: 'fall-detection-project-c06ac.firebaseapp.com',
    storageBucket: 'fall-detection-project-c06ac.firebasestorage.app',
  );
}
