name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Herramientas de Diana (Base de datos y Almacenamiento)
  shared_preferences: ^2.5.5
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1

  # Herramientas de Nahomi (Bluetooth)
  flutter_blue_plus: ^1.31.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # Activa el uso de imágenes/logos que Diana diseñó
  assets:
    - assets/logo.png

  uses-material-design: true